# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(775, 650)
        MainWindow.setMinimumSize(QtCore.QSize(775, 650))
        MainWindow.setMaximumSize(QtCore.QSize(775, 650))
        MainWindow.setStyleSheet("background-color: rgb(249, 213, 255);\n"
"background-color: rgb(223, 218, 60);\n"
"backgroundcolor: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(1000, 1000))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("border-image: url(:/resimler/pizza.jpg);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 761, 361))
        font = QtGui.QFont()
        font.setFamily("Gill Sans Ultra Bold")
        font.setPointSize(110)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.frame)
        self.degis = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.degis.setFont(font)
        self.degis.setStyleSheet("QPushButton {\n"
"    font-size: 18px;\n"
"    background-color: #89660c;\n"
"    color: #000000;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #0b9e16;\n"
"    font-weight: bold;\n"
"    padding: 8px;\n"
"    box-shadow: 2px 2px 5px rgba(0,0,0,0.3);  \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #b7810c;\n"
"}")
        self.degis.setObjectName("degis")
        self.verticalLayout.addWidget(self.degis)
        self.ara = QtWidgets.QPushButton(self.centralwidget)
        self.ara.setStyleSheet("QPushButton {\n"
"    font-size: 18px;\n"
"    background-color: #89660c;\n"
"    color: #000000;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #0b9e16;\n"
"    font-weight: bold;\n"
"    padding: 8px;\n"
"    box-shadow: 2px 2px 5px rgba(0,0,0,0.3);  \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #b7810c;\n"
"}")
        self.ara.setObjectName("ara")
        self.verticalLayout.addWidget(self.ara)
        self.gor = QtWidgets.QPushButton(self.centralwidget)
        self.gor.setStyleSheet("QPushButton {\n"
"    font-size: 18px;\n"
"    background-color: #89660c;\n"
"    color: #000000;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #0b9e16;\n"
"    font-weight: bold;\n"
"    padding: 8px;\n"
"    box-shadow: 2px 2px 5px rgba(0,0,0,0.3);  \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #b7810c;\n"
"}")
        self.gor.setObjectName("gor")
        self.verticalLayout.addWidget(self.gor)
        self.ver = QtWidgets.QPushButton(self.centralwidget)
        self.ver.setStyleSheet("QPushButton {\n"
"    font-size: 18px;\n"
"    background-color: #89660c;\n"
"    color: #000000;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #0b9e16;\n"
"    font-weight: bold;\n"
"    padding: 8px;\n"
"    box-shadow: 2px 2px 5px rgba(0,0,0,0.3);  \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #b7810c;\n"
"}")
        self.ver.setObjectName("ver")
        self.verticalLayout.addWidget(self.ver)
        self.sil = QtWidgets.QPushButton(self.centralwidget)
        self.sil.setStyleSheet("QPushButton {\n"
"    font-size: 18px;\n"
"    background-color: #89660c;\n"
"    color: #000000;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #0b9e16;\n"
"    font-weight: bold;\n"
"    padding: 8px;\n"
"    box-shadow: 2px 2px 5px rgba(0,0,0,0.3);  \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #b7810c;\n"
"}")
        self.sil.setObjectName("sil")
        self.verticalLayout.addWidget(self.sil)
        self.frame.raise_()
        self.gor.raise_()
        self.ara.raise_()
        self.sil.raise_()
        self.ver.raise_()
        self.degis.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 775, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Pizzashi"))
        self.ver.setText(_translate("MainWindow", "Sipariş Ver"))
        self.ara.setText(_translate("MainWindow", "Sipariş Ara"))
        self.gor.setText(_translate("MainWindow", "Siparişleri Gör"))
        self.degis.setText(_translate("MainWindow", "Siparişini Değiştir"))
        self.sil.setText(_translate("MainWindow", "Sipariş Sil"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
