# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'siparis_ver.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(775, 650)
        MainWindow.setMinimumSize(QtCore.QSize(775, 650))
        MainWindow.setMaximumSize(QtCore.QSize(775, 650))
        MainWindow.setStyleSheet("background-color: rgb(249, 213, 255);\n"
"background-color: rgb(223, 218, 60);\n"
"backgroundcolor: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.username_input = QtWidgets.QTextEdit(self.centralwidget)
        self.username_input.setGeometry(QtCore.QRect(153, 20, 591, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.username_input.setFont(font)
        self.username_input.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.username_input.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.username_input.setObjectName("username_input")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 110, 471, 91))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.kasar = QtWidgets.QCheckBox(self.centralwidget)
        self.kasar.setGeometry(QtCore.QRect(50, 200, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.kasar.setFont(font)
        self.kasar.setObjectName("kasar")
        self.sucuk = QtWidgets.QCheckBox(self.centralwidget)
        self.sucuk.setGeometry(QtCore.QRect(50, 260, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.sucuk.setFont(font)
        self.sucuk.setObjectName("sucuk")
        self.mantar = QtWidgets.QCheckBox(self.centralwidget)
        self.mantar.setGeometry(QtCore.QRect(50, 310, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.mantar.setFont(font)
        self.mantar.setObjectName("mantar")
        self.zeytin = QtWidgets.QCheckBox(self.centralwidget)
        self.zeytin.setGeometry(QtCore.QRect(300, 210, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.zeytin.setFont(font)
        self.zeytin.setObjectName("zeytin")
        self.misir = QtWidgets.QCheckBox(self.centralwidget)
        self.misir.setGeometry(QtCore.QRect(300, 260, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.misir.setFont(font)
        self.misir.setObjectName("misir")
        self.biber = QtWidgets.QCheckBox(self.centralwidget)
        self.biber.setGeometry(QtCore.QRect(300, 310, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.biber.setFont(font)
        self.biber.setObjectName("biber")
        self.kavurma = QtWidgets.QCheckBox(self.centralwidget)
        self.kavurma.setGeometry(QtCore.QRect(520, 210, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.kavurma.setFont(font)
        self.kavurma.setObjectName("kavurma")
        self.pastirma = QtWidgets.QCheckBox(self.centralwidget)
        self.pastirma.setGeometry(QtCore.QRect(520, 260, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pastirma.setFont(font)
        self.pastirma.setObjectName("pastirma")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(540, 310, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 430, 411, 121))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    font-size: 40px;\n"
"    background-color: #89660c;\n"
"    color: #000000;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #0b9e16;\n"
"    font-weight: bold;\n"
"    padding: 8px;\n"
"    box-shadow: 2px 2px 5px rgba(0,0,0,0.3);  \n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #b7810c;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 775, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Adınız"))
        self.label_2.setText(_translate("MainWindow", "İstediğiniz Malzemeler"))
        self.kasar.setText(_translate("MainWindow", "Kaşar "))
        self.sucuk.setText(_translate("MainWindow", "Sucuk"))
        self.mantar.setText(_translate("MainWindow", "Mantar"))
        self.zeytin.setText(_translate("MainWindow", "Zeytin"))
        self.misir.setText(_translate("MainWindow", "Mısır"))
        self.biber.setText(_translate("MainWindow", "Biber"))
        self.kavurma.setText(_translate("MainWindow", "Kavurma"))
        self.pastirma.setText(_translate("MainWindow", "Pastırma"))
        self.label_3.setText(_translate("MainWindow", "Ananas"))
        self.pushButton.setText(_translate("MainWindow", "Sipariş Ver"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
